!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  base_global_planner: navfn/NavfnROS
  base_local_planner: teb_local_planner/TebLocalPlannerROS
  clearing_rotation_allowed: true
  conservative_reset_dist: 3.0
  controller_frequency: 10.0
  controller_patience: 15.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      base_global_planner: navfn/NavfnROS
      base_local_planner: teb_local_planner/TebLocalPlannerROS
      clearing_rotation_allowed: true
      conservative_reset_dist: 3.0
      controller_frequency: 10.0
      controller_patience: 15.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      make_plan_add_unreachable_goal: true
      make_plan_clear_costmap: true
      max_planning_retries: -1
      name: Default
      oscillation_distance: 0.5
      oscillation_timeout: 5.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      planner_frequency: 5.0
      planner_patience: 5.0
      recovery_behavior_enabled: true
      restore_defaults: false
      shutdown_costmaps: false
      state: true
      type: ''
    state: []
  make_plan_add_unreachable_goal: true
  make_plan_clear_costmap: true
  max_planning_retries: -1
  oscillation_distance: 0.5
  oscillation_timeout: 5.0
  planner_frequency: 5.0
  planner_patience: 5.0
  recovery_behavior_enabled: true
  restore_defaults: false
  shutdown_costmaps: false
state: []
