!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 8.0
  acc_lim_trans: 0.2
  acc_lim_x: 0.3
  acc_lim_y: 0.0
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 20.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 8.0
      acc_lim_trans: 0.2
      acc_lim_x: 0.3
      acc_lim_y: 0.0
      angular_sim_granularity: 0.1
      forward_point_distance: 0.325
      goal_distance_bias: 20.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_scaling_factor: 0.2
      max_vel_theta: 1.0
      max_vel_trans: 0.4
      max_vel_x: 0.4
      max_vel_y: 0.0
      min_vel_theta: 0.7
      min_vel_trans: 0.28
      min_vel_x: 0.3
      min_vel_y: 0.0
      name: Default
      occdist_scale: 0.1
      oscillation_reset_angle: 0.2
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      path_distance_bias: 30.0
      prune_plan: true
      restore_defaults: false
      scaling_speed: 0.25
      sim_granularity: 0.025
      sim_time: 3.0
      state: true
      stop_time_buffer: 0.2
      theta_stopped_vel: 0.7
      trans_stopped_vel: 0.25
      twirling_scale: 0.0
      type: ''
      use_dwa: true
      vth_samples: 40
      vx_samples: 20
      vy_samples: 1
      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 0.2
    state: []
  max_scaling_factor: 0.2
  max_vel_theta: 1.0
  max_vel_trans: 0.4
  max_vel_x: 0.4
  max_vel_y: 0.0
  min_vel_theta: 0.7
  min_vel_trans: 0.28
  min_vel_x: 0.3
  min_vel_y: 0.0
  occdist_scale: 0.1
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 30.0
  prune_plan: true
  restore_defaults: false
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 3.0
  stop_time_buffer: 0.2
  theta_stopped_vel: 0.7
  trans_stopped_vel: 0.25
  twirling_scale: 0.0
  use_dwa: true
  vth_samples: 40
  vx_samples: 20
  vy_samples: 1
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.2
state: []
