local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
  transform_tolerance: 0.5
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}

######################################################

# local_costmap:
#   global_frame: map
#   robot_base_frame: base_link

#   update_frequency: 1.0
#   publish_frequency: 1.0
#   transform_tolerance: 0.5  

#   static_map: false  
#   rolling_window: true
#   width: 3
#   height: 3
#   resolution: 0.05
#   track_unknown_space: false
