spotD:
  position: 
    x: 6.77251315644
    y: 9.07628821387
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: -0.799664231489
    w: 0.60044743057

spotA:
  position: 
    x: 1.18118164981
    y: 2.69529448689
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: -0.330821074961
    w: 0.943693497043

spotC:
  position: 
    x: 4.1614585521
    y: 7.54957997905
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: -0.182515379898
    w: 0.983202998419

spotB:
  position: 
    x: 4.85250933552
    y: 4.22522555968
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.989507991438
    w: 0.144478146724
