TrajectoryPlannerROS:
    acc_lim_x: 0.2 # (2.5) The x acceleration limit of the robot in meters/sec^2.
    acc_lim_y: 0.0 # (2.5) The y acceleration limit of the robot in meters/sec^2.
    acc_lim_theta: 5.0 # (3.2) The rotational acceleration limit of the robot in radians/sec^2. 

    max_vel_x: 0.4 # (0.5) The maximum forward velocity allowed for the base in meters/sec.
    min_vel_x: 0.15 # (0.1) The minimum forward velocity allowed for the base in meters/sec. It is useful to specify this to guarantee that velocity commands sent to a mobile base are high enough to allow the base to overcome friction.
    max_vel_theta: 1.0 # (1.0) The maximum rotational velocity allowed for the base in radians/sec.
    min_vel_theta: -1.0 # (-1.0) The minimum rotational velocity allowed for the base in radians/sec. 
    min_in_place_vel_theta: 0.7 # (0.4) The minimum rotational velocity allowed for the base while performing in-place rotations in radians/sec.
    escape_vel: -0.15 # (-0.1) Speed used for driving during escapes in meters/sec. Note that it must be negative in order for the robot to actually reverse. A positive speed will cause the robot to move forward while attempting to escape.

    holonomic_robot: false # (true) Determines whether velocity commands are generated for a holonomic or non-holonomic robot. For holonomic robots, strafing velocity commands may be issued to the base. For non-holonomic robots, no strafing velocity commands will be issued.

    yaw_goal_tolerance: 0.3 # (0.05) The tolerance in radians for the controller in yaw/rotation when achieving its goal.
    xy_goal_tolerance: 0.3 # (0.10) The tolerance in meters for the controller in the x & y distance when achieving a goal.
    latch_xy_goal_tolerance: true # (false) If goal tolerance is latched, if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.

    sim_time: 3.0 # (1.0) The amount of time to forward-simulate trajectories in seconds.
    sim_granularity: 0.025 # (0.025) The step size, in meters, to take between points on a given trajectory.
    angular_sim_granularity: 0.025 # (sim_granularity) The step size, in radians, to take between angular samples on a given trajectory.
    vx_samples: 3 # (3) The number of samples to use when exploring the x velocity space.
    vtheta_samples: 20 # (20) The number of samples to use when exploring the theta velocity space.

    meter_scoring: true # (false) Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default.
    
    pdist_scale: 0.6 # (0.6) The weighting for how much the controller should stay close to the path it was given, maximal possible value is 5.0.
    gdist_scale: 5.0 # (0.8) The weighting for how much the controller should attempt to reach its local goal, also controls speed, maximal possible value is 5.0.
    occdist_scale: 5.0 # (0.01) The weighting for how much the controller should attempt to avoid obstacles.
    
    heading_lookahead: 0.325 # (0.325) How far to look ahead in meters when scoring different in-place-rotation trajectories.
    heading_scoring: false # (false) Whether to score based on the robot's heading to the path or its distance from the path.
    heading_scoring_timestep: 0.8 # (0.8) How far to look ahead in time in seconds along the simulated trajectory when using heading scoring.
    
    dwa: false # (true) Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout.
    publish_cost_grid_pc: true # (false) Whether or not to publish the cost grid that the planner will use when planning. When true, a sensor_msgs/PointCloud2 will be available on the ~<name>/cost_cloud topic. Each point cloud represents the cost grid and has a field for each individual scoring function component as well as the overall cost for each cell, taking the scoring parameters into account.
    global_frame_id: "odom" # ("odom") The frame to set for the cost_cloud. Should be set to the same frame as the local costmap's global frame.