recovery_behavior_enabled: true
conservative_reset_dist: 3.0
clearing_rotation_allowed: true
shutdown_costmaps: false
controller_frequency: 10.0
controller_patience: 15.0
planner_frequency: 5.0
planner_patience: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

